### ISSUE TITLE
crash at the end of the round

### ISSUE THREAD

**Issue by mattymatty97** [NeonWizard/SCP-DisconnectDrop#4]
at the end of the round the plugin will try to drop the items of all the connected players and will crash the server

**Comment by NeonWizard** [comment]
Should be fixed in [v1.6.0](https://github.com/NeonWizard/SCP-DisconnectDrop/releases/tag/1.6.0).

**Comment by NeonWizard** [comment]
```
Receiving unhandled NULL exception
#0  0x007ff9759ccac0 in funlockfile
#1  0x007ffe1303cd98 in operator new[](unsigned long, std::nothrow_t const&)
#2  0x007ffe1303cda0 in operator new[](unsigned long, std::nothrow_t const&)
#3  0x007ffe1303cdb0 in operator new[](unsigned long, std::nothrow_t const&)
#4  0x007ffe1303cdc0 in operator new[](unsigned long, std::nothrow_t const&)
#5  0x007ffe1303cde0 in operator new[](unsigned long, std::nothrow_t const&)
#6  0x007ffe1303ce00 in operator new[](unsigned long, std::nothrow_t const&)
#7  0x007ffe1303d640 in operator new[](unsigned long, std::nothrow_t const&)
#8  0x007ffe1303d750 in operator new[](unsigned long, std::nothrow_t const&)
#9  0x007ffe1303d7c0 in operator new[](unsigned long, std::nothrow_t const&)
#10 0x007ffe1303d8a0 in operator new[](unsigned long, std::nothrow_t const&)
#11 0x007ffe1303d8d0 in operator new[](unsigned long, std::nothrow_t const&)
#12 0x007ffe1303d930 in operator new[](unsigned long, std::nothrow_t const&)
#13 0x007ffe1303d970 in operator new[](unsigned long, std::nothrow_t const&)
#14 0x007ffe1303dae0 in operator new[](unsigned long, std::nothrow_t const&)
#15 0x007ffe1303dc50 in operator new[](unsigned long, std::nothrow_t const&)
#16 0x007ffe1303dcd0 in oc_frag_recon_inter2_c
#17 0x007ffe1303e240 in __libc_start_main
#18 0x007ffe1303e300 in oc_frag_recon_inter2_c
```

Stacktrace reported by user with the issue.

**Comment by NeonWizard** [comment]
Closed in suspicion of this being unrelated to the plugin.
